# A headless service to create DNS records
---
apiVersion: v1
kind: Service
metadata:
  name: kaf-hl 
  namespace: kafka-test
spec:
  ports:
  - port: 9092
  # [podname].broker.kafka.svc.cluster.local
  clusterIP: None
  selector:
    app: kafka-uat
