kind: Service
apiVersion: v1
metadata:
  name: zoo1
  namespace: kafka-test
spec:
  type: NodePort
  ports:
  - name: port-2181
    port: 2181
    protocol: TCP 
  - name: port-2888
    port: 2888
    protocol: TCP 
  - name: port-3888
    port: 3888
    protocol: TCP 
  selector:
    app: zk-uat

---
kind: Service
apiVersion: v1
metadata:
  name: zoo2
  namespace: kafka-test
spec:
  type: NodePort
  ports:
  - name: port-2181
    port: 2181
    protocol: TCP 
  - name: port-2888
    port: 2888
    protocol: TCP 
  - name: port-3888
    port: 3888
    protocol: TCP 
  selector:
    app: zk-uat
---
kind: Service
apiVersion: v1
metadata:
  name: zoo3
  namespace: kafka-test
spec:
  type: NodePort
  ports:
  - name: port-2181
    port: 2181
    protocol: TCP
  - name: port-2888
    port: 2888
    protocol: TCP
  - name: port-3888
    port: 3888
    protocol: TCP
  selector:
    app: zk-uat
---
