# the headless service is for PetSet DNS, this one is for clients
apiVersion: v1
kind: Service
metadata:
  name: zoo-hl
  namespace: kafka-test
spec:
  ports:
  - port: 2181
    name: client
  selector:
    app: zk-uat
