apiVersion: v1
kind: Service
metadata:
  name: kaf1
  namespace: kafka-test
  labels:
    app: kaf1
spec:
  type: NodePort
  ports:
  - port: 9092
    name: kaf1
    targetPort: 9092
    nodePort: 30901
    protocol: TCP
  selector:
    app: kaf1
---
apiVersion: v1
kind: Service
metadata:
  name: kaf2
  namespace: kafka-test
  labels:
    app: kaf2
spec:
  type: NodePort
  ports:
  - port: 9092
    name: kaf2
    targetPort: 9092
    nodePort: 30902
    protocol: TCP
  selector:
    app: kafka2
---

