apiVersion: v1
kind: Pod
metadata:
  name: kafka-cli
  namespace: kafka-test
spec:
  containers:
  - name: kafka
    image: solsson/kafka:0.11.0.0
    imagePullPolicy: IfNotPresent
    command:
      - sh
      - -c
      - "exec tail -f /dev/null"
