apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: kafka-test-stg-sc-replication3
parameters:
  group: kafka_test_vg
  io_priority: high
  repl: '3'
provisioner: alicloud/disk
reclaimPolicy: Delete
volumeBindingMode: Immediate
