kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: kafka-test-stg-sc
provisioner: kubernetes.io/no-provisioner
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: kafka-test-stg-sc-replication3
provisioner: kubernetes.io/no-provisioner

