apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-pv-claim-stg-sc
spec:
  storageClassName: kafka-stg-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zk-pvclaim-kafka-stg-sc
spec:
  storageClassName: kafka-stg-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadir-zk-1
spec:
  storageClassName: kafka-stg-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
