apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv-stg-sc
  labels:
    type: local
spec:
  storageClassName: kafka-stg-sc
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/kafka"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zk-pv-stg-sc
  labels:
    type: local
spec:
  storageClassName: kafka-stg-sc
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/zookeeper"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv-0
  labels:
    type: local
spec:
  storageClassName: kafka-stg-sc
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/kafka"

