kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: kafka-stg-sc
provisioner: alicloud/disk
parameters:
  repl: "1"
  io_priority: "high"
  group: "zk_vg"
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: kafka-stg-sc-rep3
provisioner: alicloud/disk
parameters:
  repl: "3"
  io_priority: "high"
  group: "kafka_vg"