kind: Service
apiVersion: v1
metadata:
  name: outside-2
  namespace: kafka-uat
spec:
  selector:
    app: kafka
  ports:
  - protocol: TCP
    targetPort: 9094
    port: 32402
    nodePort: 32402
  type: NodePort
