kind: Service
apiVersion: v1
metadata:
  name: outside-1
  namespace: kafka-uat
spec:
  selector:
    app: kafka
  ports:
  - protocol: TCP
    targetPort: 9094
    port: 32401
    nodePort: 32401
  type: NodePort
