kind: Service
apiVersion: v1
metadata:
  name: inside-0
  namespace: kafka-test
spec:
  selector:
    app: kafka
    kafka-broker-id: "0"
  ports:
  - protocol: TCP
    targetPort: 9094
    port: 32400
    nodePort: 32400
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - ip: 10.161.17.203
